export const IMAGES = {
  ic_logo: require('./ic_logo.png'),
  ic_back: require('./ic_back.png'),
  ic_down: require('./ic_down.png'),
  ic_hide: require('./ic_hide.png'),
  ic_show: require('./ic_show.png'),
  plus: require('./plus.png'),
  home_unselected: require('./home_unselected.png'),
  profile_unselected: require('./profile_unselected.png'),
  chat_unselected: require('./chat_unselected.png'),
  request_unselected : require('./request_unselected.png'),
  ic_check: require('./ic_check.png'),
  ic_sealCheck: require('./ic_sealCheck.png'),
  ic_credit_card: require('./ic_credit_card.png'),
  ic_google_pay: require('./ic_google_pay.png'),
  ic_apple_pay: require('./ic_apple_pay.png'),
  ic_right: require('./ic_right.png'),
  ic_success: require('./ic_success.png'),
  ic_info: require('./ic_info.png'),
  ic_file_uplord: require('./ic_file_uplord.png'),
  ic_hammer_wrench: require('./ic_hammer_wrench.png'),
  ic_radio_unselect: require('./ic_radio_unselect.png'),
  ic_radio_select: require('./ic_radio_select.png'),
  ic_checkBox_unSelect: require('./ic_checkBox_unSelect.png'),
  ic_checkbox_select: require('./ic_checkbox_select.png'),
  ic_delete: require('./ic_delete.png'),
  accountSuccessfully: require('./accountSuccessfully.png'),
};
