import { stubString } from 'lodash';
import {useTranslation} from 'react-i18next';

export const useString = () => {
  return {
    welcome_back : 'Welcome Back!',
    enter_your_email_and_password_to_login : 'Enter your email and password to login',
    email_or_mobile_number : 'Email/ Mobile No',
    enter_email_or_mobile_number : 'Enter Email/ Mobile No',
    password : 'Password',
    enter_password : 'Enter Password',
    forgot_password : 'Forgot Password?',
    login : 'Login',
    dont_have_an_account : "Don't have an account?",
    sign_up : 'Sign Up',
    please_enter_your_email : 'Please enter your email',
    please_enter_your_password : 'Please enter your password',
    please_enter_your_name : 'Please enter your name',
    please_enter_your_mobile_number : 'Please enter your mobile number',
    create_account : 'Create Account',
    already_have_an_account : 'Already have an account?',
    reset_password : 'Reset Password',
    enter_your_registered_email_or_phone_number_below_to_get_reset_your_password : 'Enter your Registered Email or Phone Number below to get reset your password.',
    continue: "Continue",
    To_reset_your_password_Please_enter_the_4_Digit_PIN_sent_to_your_Email_or_Phone_Number: "To reset your password. Please enter the 4 Digit PIN sent to your Email or Phone Number.",
    code: "Code",
    resend_code: "Resend code",
    Your_new_password_must_be_different_from_previously_used_passwords: "Your new password must be different from previously used passwords",
    enter_new_password: "Enter New Password",
    re_enter_new_password: "Re-enter New Password",
    set_new_password: "Set New Password",
    coudPouss: "CoudPouss",
    Empowering_seniors_with_easy_access_to_trusted_help_care_and_companionship_whenever_needed: "Empowering seniors with easy access to trusted help, care, and companionship whenever needed.",
    Sign_up_as_Elder: "Sign up as Elder",
    Sign_up_as_Professional: "Sign up as Professional",
    or: "OR",
    get_started_now: "Get Started Now",
    log_in: "Log In",
    enter_OTP: "Enter OTP",
    verify_OTP: "Verify OTP",
    create_password: "Create Password",
    create_a_strong_password: "Create a strong password",
    next: "Next",
    confirm_password: "Confirm Password",
    add_personal_details: "Add Personal Details",
    enter_profile_details: "Enter profile details",
    name: "Name",
    enter_name: "Enter Name",
    mobile_no: "Mobile No.",
    enter_mobile_no: "Enter Mobile No.",
    email: "Email",
    enter_email: "Enter Email",
    bc: "BC",
    upload_profile_picture: "Upload profile picture",
    address: "Address",
    enter_address: "Enter Address",
    choose_your_subscription: "Choose your subscription",
    select_the_plan_that_fits_your_activity_You_can_change_it_later_in_your_profile: "Select the plan that fits your activity. You can change it later in your profile.",
    professional_certified: "Professional (Certified)",
    subscribe: "Subscribe",
    skip: "Skip",
    monthly: "Monthly",
    billed_recurring_monthly_cancel_anytime: "*Billed & recurring monthly cancel anytime",
    non_certified_provider: "Non-Certified Provider",
    all_premium_plans: "All Premium Plans",
    subscribe_text: "Your membership starts as soon as you set up payment and subscribe. Your monthly charge will occur on the last day of the current billing period. We’ll renew your membership for you can manage your subscription or turn off auto-renewal under accounts setting.\n\nBy continuing, you are agreeing to these terms. See the privacy statement and restricions.",
    please_select_a_plan: "Please select a plan",
    selected_plan_details: "Selected Plan Details",
    start_your_journey_today_first_month_on_Us: "Start Your Journey Today –\nFirst Month on Us!",
    subscription_details_text: "Subscribe now and enjoy your first month completely free. No payment today – your subscription will start immediately, and you’ll be charged only after 30 days.",
    earn_money_through_coudPouss_secure_escrow_payments: "Earn money through CoudPouss (secure escrow payments)",
    certified_badge_visible_to_all_clients: "Certified Badge visible to all clients",
    includes_1_service_category_1_per_extra_category: "Includes 1 service category, +€1 per extra category:",
    subscription_billed_via_Bank_Card_Google_Pay_or_Apple_Pay: "Subscription billed via Bank Card, Google Pay, or Apple Pay:",
    profile_reviewed_within_72_hours_by_an_administrator: "Profile reviewed within 72 hours by an administrator",
    back: "Back",
    payment_method: "Payment Method",
    select_a_quick_and_secure_way_to_complete_your_subscription: "Select a quick and secure way to complete your subscription.",
    proceed_to_pay: "Proceed to Pay",
    cancel: "Cancel",
    choose_payment_method: "Choose payment method",
    complete_profile_now: "Complete Profile Now",
    subscription_successful: "Subscription Successful",
    welcome_aboard_your_subscription_is_now_active_you_can_start_exploring_all_features_immediately: "Welcome aboard! Your subscription is now active. You can start exploring all features immediately.",
    subcription_details: "Subcription Details",
    plan: "Plan",
    mode_of_payment: "Mode of Payment",
    transaction_id: "Transaction ID",
    start_date: "Start Date",
    billing_cycle: "Billing Cycle",
    first_charge_date: "First Charge Date",
    info: "Info",
    no_paymentwas_taken_today_your_first_month_is_free: "No payment was taken today – your first month is free.",
    upload_the_required_documents_to_complete_your_profile_and_gain_the_Certified_badge: "Upload the required documents to complete your profile and gain the Certified badge.",
    upload_from_device: "upload from device",
    a_copy_of_ID: "A copy of ID",
    kbis_extract: "Kbis Extract",
    proof_of_residence : "Proof of residence",
    less_than_3_months_old_e_g_water_or_electricity_bill: "*less than 3 months old (e.g., water or electricity bill)",
    additional_details: "Additional Details",
    years_of_experience: "Years of Experience",
    tell_us_more_about_your_professional_background_Enter_your_years_of_experience_to_showcase_your_expertise: "Tell us more about your professional background. Enter your years of experience to showcase your expertise.",
    experience: "Experience",
    add_services: "Add Services",
    select_a_category : "Select A Category",
    choose_a_category_that_best_matches_your_services_This_helps_us_connect_you_with_the_right_clients: "Choose a category that best matches your services. This helps us connect you with the right clients.",
    select_category: "Select a category"
  };
};

export function getTranslation(str: string) {
  const {t} = useTranslation();
  return t(str);
}
