import {useTranslation} from 'react-i18next';

export const useString = () => {
  return {
    welcome_back : 'Welcome Back!',
    enter_your_email_and_password_to_login : 'Enter your email and password to login',
    email_or_mobile_number : 'Email/ Mobile No',
    enter_email_or_mobile_number : 'Enter Email/ Mobile No',
    password : 'Password',
    enter_password : 'Enter Password',
    forgot_password : 'Forgot Password?',
    login : 'Login',
    dont_have_an_account : "Don't have an account?",
    sign_up : 'Sign Up',
    please_enter_your_email : 'Please enter your email',
    please_enter_your_password : 'Please enter your password',
    please_enter_your_name : 'Please enter your name',
    please_enter_your_mobile_number : 'Please enter your mobile number',
    create_account : 'Create Account',
    already_have_an_account : 'Already have an account?',
    reset_password : 'Reset Password',
    enter_your_registered_email_or_phone_number_below_to_get_reset_your_password : 'Enter your Registered Email or Phone Number below to get reset your password.',
    continue: "Continue",
    To_reset_your_password_Please_enter_the_4_Digit_PIN_sent_to_your_Email_or_Phone_Number: "To reset your password. Please enter the 4 Digit PIN sent to your Email or Phone Number.",
    code: "Code",
    resend_code: "Resend code",
    Your_new_password_must_be_different_from_previously_used_passwords: "Your new password must be different from previously used passwords",
    enter_new_password: "Enter New Password",
    re_enter_new_password: "Re-enter New Password",
    set_new_password: "Set New Password",
    coudPouss: "CoudPouss",
    Empowering_seniors_with_easy_access_to_trusted_help_care_and_companionship_whenever_needed: "Empowering seniors with easy access to trusted help, care, and companionship whenever needed.",
    Sign_up_as_Elder: "Sign up as Elder",
    Sign_up_as_Professional: "Sign up as Professional",
    or: "OR",
    get_started_now: "Get Started Now",
    log_in: "Log In",
    enter_OTP: "Enter OTP",
    verify_OTP: "Verify OTP",
    create_password: "Create Password",
    create_a_strong_password: "Create a strong password",
    next: "Next",
    confirm_password: "Confirm Password",
    add_personal_details: "Add Personal Details",
    enter_profile_details: "Enter profile details",
    name: "Name",
    enter_name: "Enter Name",
    mobile_no: "Mobile No.",
    enter_mobile_no: "Enter Mobile No.",
    email: "Email",
    enter_email: "Enter Email",
    bc: "BC",
    upload_profile_picture: "Upload profile picture",
    address: "Address",
    enter_address: "Enter Address",
    choose_your_subscription: "Choose your subscription",
    select_the_plan_that_fits_your_activity_You_can_change_it_later_in_your_profile: "Select the plan that fits your activity. You can change it later in your profile.",
    professional_certified: "Professional (Certified)"
  };
};

export function getTranslation(str: string) {
  const {t} = useTranslation();
  return t(str);
}
