const API_BASE_URL = "http://163.227.92.122:4001/"

const DISABLE_API_LOGS = false

const API_ROUTES = {
    login: 'userService/auth/login',
    signup: 'userService/auth/start',
    verifyOtp: 'userService/auth/verify',
    resendOtp: 'userService/auth/resend-otp',
    createPassword: 'userService/auth/password',
    addPersonalDetails: 'userService/auth/details',
    resetPassword: 'userService/auth/reset/start',
    verifyResetPassword: 'userService/auth/reset/verify',
    createNewPassword: 'userService/auth/reset/confirm',
    getUserDetails: 'userService/auth/get_user',
    uploadProfileImage: 'userService/auth/upload-profile-photo',
    getHomeData: "home_module/home",
    getAllPlans: "userService/auth/plans/all",
    getPlanDetails: "userService/auth/plans",
    uploadDocuments: 'userService/auth/provider/upload-documents',
    addYearsOfExperience: 'userService/auth/experience',
    onSelectPlan: "userService/auth/select-plan",
    allCategories: "home_module/all_categories",
    uploadServiceRequestImage: "service_request/upload-job-file",
    editProfile: "profile_module/profile",
    onServiceRequest: "service_request/service-requests",
    ratingAndReviews: "elderly_profile/profile?section=ratings_reviews",
    deleteProfile: "elderly_profile/profile?section=my_profile",
    getAllRequests: "service_confirmation/service_accept/get_services",
    onSelectedCategories: "userService/auth/select-categories",
    onSelectedServices: "userService/auth/select-sub-categories",
    getServiceDetails: "service_confirmation/service_accept/get_service",
    getFavoriteProfessionals: "service_confirmation/favorite-provider/fetch",
    onSendCategoryIds: "userService/auth/select-provider-services",
    fetchTransactions: "profile_module/user_profile",
    getProfessionalAllServices: "quote_request/open-services",
    getProfessionalServiceDetails: "quote_request/service-info",
    sendQuoteRequest: "quote_request/quoterequest",
    fileUploadProfessionalServices:"quote_request/upload-job-file",
    uploadProviderJobFiles: "profile_module/upload-files",
    getProviderUserDetails: "service_confirmation/service_accept/provider_user",
    getQuateList: "quote_accept/service-provider/quotes",
    addFavoriteProfessional: "service_confirmation/favorite-provider/add",
    removeFavoriteProfessional: "service_confirmation/favorite-provider/remove",
    onServiceReject: "service_confirmation/service_accept/reject_quote",
    getServiceAmount: "service_confirmation/service_accept/amounts",
    onAcceptService: "service_confirmation/service_accept/accept_quote",
    getServicePaymentDetails: "service_confirmation/service_accept/payment-details",
    otherUserProfile: "service_confirmation/service_accept/user",
    confirmPayment: "service_confirmation/service_accept/confirm-payment",
    onWriteReview: "service_confirmation/ratings/submit?type=both",
    getCancelServiceDetails: "service_request/get-payment",
    onCancelService: "service_request/cancel",
    getAllService: "userService/auth/get-selected-services",
    getTsakDetails: "quote_accept/service-provider",
    getRefreshToken: "userService/auth/refresh-token",
    subscriptionPayment: "subscription_and_payment/subscription/select-plan",
    getTaskStatus: "quote_accept/service-provider/task-status",
}


export { API_ROUTES, API_BASE_URL, DISABLE_API_LOGS }